#!/bin/bash

BASE=$(dirname $0)
HOSTNAME=$(hostname)

stop_by_pidfile () {
    pidfile="$1"; shift
    name="$1";    shift
    pid=`cat "$pidfile" 2>/dev/null`
    echo "Stopping $name... ($pid)"
    stop_pid "$pid"
}

stop_by_pid () {
    pid="$1";  shift
    name="$1"; shift
    echo "Stopping $name... ($pid)"
    stop_pid "$pid"
}

stop_pid () {
    pid="$1"; shift
    if [[ -n "$pid" ]]; then
        if kill -TERM "$pid"; then
            echo " OK."
            n_tries=0
            while [[ $n_tries -lt 5 ]]; do
                sleep 1
                if kill -0 "$pid" 2>/dev/null; then
                    true;
                else
                    n_tries=5   # end loop
                fi
                (( n_tries = n_tries + 1 ))
            done
        else
            echo " ERROR."
        fi
    else
        echo " not running."
    fi  
}

APP_PID="$BASE/pid/application.pid"

stop_by_pidfile $APP_PID "Application"

